class AppStrings {
  AppStrings._();

  static const String appName = 'Parvaah';
  static const String appTagline = 'Smart Safety & Early Warning';
  static const String appSubtitle =
      'AI-Based Early Warning and Landslide Risk Monitoring System';
  static const String motto = 'Safer People • Safer Roads • Safer Communities';

  // 8 Regional languages for North Eastern India
  static const Map<String, String> supportedLanguages = {
    'en': 'English',
    'hi': 'हिन्दी (Hindi)',
    'as': 'অসমীয়া (Assamese)',
    'bn': 'বাংলা (Bengali)',
    'mni': 'মৈতৈলোন্ (Manipuri)',
    'kha': 'Khasi (Meghalaya)',
    'lus': 'Mizo ṭawng (Mizoram)',
    'nag': 'Nagamese (Nagaland)',
  };

  // Common UI Strings
  static const Map<String, Map<String, String>> localizedValues = {
    'en': {
      'stay_informed': 'Stay Informed, Stay Safer',
      'onboarding_desc':
          'Get real-time landslide risk alerts, road updates and weather information for North East India.',
      'welcome_back': 'Welcome Back',
      'sign_in_continue': 'Sign in to continue',
      'email_address': 'Email address',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'sign_in': 'Sign In',
      'or_continue_with': 'Or continue with',
      'continue_google': 'Continue with Google',
      'continue_phone': 'Continue with Phone',
      'dont_have_account': "Don't have an account?",
      'sign_up': 'Sign Up',
      'search_placeholder': 'Search location, district, or road...',
      'high_landslide_risk': 'High Landslide Risk',
      'in_nearby_areas': 'In 2 nearby areas',
      'view_details': 'View Details',
      'todays_overview': "Today's Overview",
      'high_risk_areas': 'High Risk Areas',
      'affected_roads': 'Affected Roads',
      'safe_routes': 'Safe Routes',
      'nearby_risk_status': 'Nearby Risk Status',
      'safety_tips': 'Safety Tips',
      'risk_map': 'Risk Map',
      'weather': 'Weather',
      'road_status': 'Road Status',
      'alerts': 'Alerts',
      'safety': 'Safety',
      'profile': 'Profile',
      'emergency_helpline': 'Disaster Helpline 1077',
    },
    'hi': {
      'stay_informed': 'सतर्क रहें, सुरक्षित रहें',
      'onboarding_desc':
          'पूर्वोत्तर भारत के लिए वास्तविक समय में भूस्खलन जोखिम अलर्ट, सड़क स्थिति और मौसम की जानकारी प्राप्त करें।',
      'welcome_back': 'वापसी पर स्वागत है',
      'sign_in_continue': 'जारी रखने के लिए साइन इन करें',
      'email_address': 'ईमेल पता',
      'password': 'पासवर्ड',
      'forgot_password': 'पासवर्ड भूल गए?',
      'sign_in': 'साइन इन करें',
      'or_continue_with': 'या इसके साथ जारी रखें',
      'continue_google': 'गूगल से जारी रखें',
      'continue_phone': 'फोन से जारी रखें',
      'dont_have_account': 'खाता नहीं है?',
      'sign_up': 'साइन अप करें',
      'search_placeholder': 'स्थान, जिला या सड़क खोजें...',
      'high_landslide_risk': 'उच्च भूस्खलन जोखिम',
      'in_nearby_areas': 'आसपास के 2 क्षेत्रों में',
      'view_details': 'विवरण देखें',
      'todays_overview': 'आज का अवलोकन',
      'high_risk_areas': 'उच्च जोखिम क्षेत्र',
      'affected_roads': 'प्रभावित सड़कें',
      'safe_routes': 'सुरक्षित मार्ग',
      'nearby_risk_status': 'आसपास की जोखिम स्थिति',
      'safety_tips': 'सुरक्षा सुझाव',
      'risk_map': 'जोखिम मानचित्र',
      'weather': 'मौसम',
      'road_status': 'सड़क स्थिति',
      'alerts': 'अलर्ट',
      'safety': 'सुरक्षा',
      'profile': 'प्रोफ़ाइल',
      'emergency_helpline': 'आपदा हेल्पलाइन 1077',
    },
    'as': {
      'stay_informed': 'অৱগত হওক, সুৰক্ষিত থাকক',
      'onboarding_desc':
          'উত্তৰ-পূব ভাৰতৰ বাবে বাস্তৱ-সময়ৰ ভূমিস্খলন সতৰ্কবাৰ্তা আৰু পথৰ তথ্য লাভ কৰক।',
      'welcome_back': 'স্বাগতম',
      'sign_in_continue': 'আগবাঢ়িবলৈ ছাইন ইন কৰক',
      'email_address': 'ইমেইল ঠিকনা',
      'password': 'পাছৱৰ্ড',
      'sign_in': 'ছাইন ইন কৰক',
      'search_placeholder': 'স্থান, জিলা বা পথ অনুসন্ধান কৰক...',
      'high_landslide_risk': 'উচ্চ ভূমিস্খলনৰ আশংকা',
      'view_details': 'বিৱৰণ চাওক',
      'todays_overview': 'আজিৰ আলোকপাত',
      'high_risk_areas': 'উচ্চ আশংকাযুক্ত অঞ্চল',
      'affected_roads': 'ক্ষতিগ্ৰস্ত পথ',
      'safe_routes': 'নিৰাপদ পথ',
      'risk_map': 'মানচিত্ৰ',
      'weather': 'বতৰ',
      'road_status': 'পথৰ অৱস্থা',
      'alerts': 'সতৰ্কবাৰ্তা',
      'safety': 'সুৰক্ষা',
      'profile': 'প্রফাইল',
    },
    'bn': {
      'stay_informed': 'সতর্ক থাকুন, নিরাপদ থাকুন',
      'onboarding_desc':
          'উত্তর-পূর্ব ভারতের জন্য রিয়েল-টাইম ভূমিধসের সতর্কতা ও আবহাওয়ার তথ্য পান।',
      'welcome_back': 'স্বাগতম',
      'sign_in_continue': 'চালিয়ে যেতে সাইন ইন করুন',
      'search_placeholder': 'স্থান, জেলা বা রাস্তা অনুসন্ধান করুন...',
      'high_landslide_risk': 'উচ্চ ভূমিধস ঝুঁকি',
      'view_details': 'বিস্তারিত দেখুন',
      'todays_overview': 'আজকের সংক্ষিপ্ত বিবরণ',
      'high_risk_areas': 'উচ্চ ঝুঁকিপূর্ণ এলাকা',
      'affected_roads': 'ক্ষতিগ্রস্ত রাস্তা',
      'safe_routes': 'নিরাপদ রুট',
      'risk_map': 'মানচিত্র',
      'weather': 'আবহাওয়া',
      'road_status': 'রাস্তার অবস্থা',
      'alerts': 'সতর্কতা',
      'safety': 'সুরক্ষা',
      'profile': 'প্রোফাইল',
    },
    'mni': {
      'stay_informed': 'চেকশিন্না লৈবীয়ু, কান্নহৌবীয়ু',
      'onboarding_desc': 'অৱাং নোংপোক ভারতকী চিং তাথরবগী ঈপাউ অমসুং লম্বীগী ফীভম।',
      'welcome_back': 'তরাম্না ওকচরি',
      'search_placeholder': 'মফম থিবীয়ু...',
      'high_landslide_risk': 'চিং তাথরবগী য়াম্না লুবা ফীভম',
      'view_details': 'অকুপ্পা য়েংবীয়ু',
      'todays_overview': 'ঙসিগী ফীভম',
      'risk_map': 'মেপ',
      'weather': 'নোংজুক',
      'road_status': 'লম্বী',
      'alerts': 'চেকশিনৱা',
      'safety': 'ঙাকথোকপা',
      'profile': 'প্রোফাইল',
    },
    'kha': {
      'stay_informed': 'Shong Suk, Shong Shngain',
      'onboarding_desc':
          'Tip shaphang ka jingtwad khyndew bad ka jinglong jong ki surok ha North East India.',
      'welcome_back': 'Pdiang Sngewbha',
      'search_placeholder': 'Wad ia ka jaka ne surok...',
      'high_landslide_risk': 'Ka Jingma ba jur ban twad khyndew',
      'view_details': 'Peit bniah',
      'todays_overview': 'Ka Jinglong mynta ka sngi',
      'risk_map': 'Map',
      'weather': 'Suiñbneng',
      'road_status': 'Surok',
      'alerts': 'Kyntu',
      'safety': 'Jingshngain',
      'profile': 'Profile',
    },
    'lus': {
      'stay_informed': 'Fimkhur la, Him rawh',
      'onboarding_desc':
          'North East India a lei min thleng thei leh kawng dinhmun hre hmasa rawh.',
      'welcome_back': 'Chibai',
      'search_placeholder': 'Hmun emaw kawng zawng rawh...',
      'high_landslide_risk': 'Lei min hlauhawm zual',
      'view_details': 'Hrechiang rawh',
      'todays_overview': 'Vawiin Dinhmun',
      'risk_map': 'Map',
      'weather': 'Khawchin',
      'road_status': 'Kawng',
      'alerts': 'Hriattirna',
      'safety': 'Himna',
      'profile': 'Profile',
    },
    'nag': {
      'stay_informed': 'Hushiar thakibi, Bhal thakibi',
      'onboarding_desc':
          'North East karone landslide aro rasta laga khobor rati-din pabi.',
      'welcome_back': 'Aapnake Swagatam',
      'search_placeholder': 'Jaga nohoi rasta bisaribi...',
      'high_landslide_risk': 'Bishi Dangor Landslide Danger',
      'view_details': 'Bhal pora sabo',
      'todays_overview': 'Aji laga Khobor',
      'risk_map': 'Map',
      'weather': 'Weather',
      'road_status': 'Rasta',
      'alerts': 'Alerts',
      'safety': 'Safety',
      'profile': 'Profile',
    },
  };

  static String get(String key, {String lang = 'en'}) {
    final langMap = localizedValues[lang] ?? localizedValues['en']!;
    return langMap[key] ?? localizedValues['en']![key] ?? key;
  }
}
