"""Seed data for road corridors and disaster management officers."""

SEED_ROADS = [
    {
        "road_id": "RD-NH-13-KAMENG",
        "name": "NH-13 Trans-Arunachal Highway (km 42-48)",
        "road_class": "national_highway",
        "zone_id": "NER-ARU-001",
        "status": "blocked",
        "blockage_reason": "Severe slope collapse near km 44. Debris removal in progress.",
        "start_point": "Bhalukpong Gate",
        "end_point": "Bomdila Pass",
        "is_single_access": True,
    },
    {
        "road_id": "RD-SH-3-UKHRUL",
        "name": "State Highway 3 (Ukhrul - Jessami)",
        "road_class": "state_highway",
        "zone_id": "NER-MAN-003",
        "status": "at_risk",
        "blockage_reason": "Multiple active debris flows along embankment cut.",
        "start_point": "Ukhrul Junction",
        "end_point": "Jessami Ridge",
        "is_single_access": False,
    },
    {
        "road_id": "RD-NH-106-SOHRA",
        "name": "Shillong - Sohra Scenic Link (Sector 4)",
        "road_class": "state_highway",
        "zone_id": "NER-MEG-002",
        "status": "at_risk",
        "blockage_reason": "High pore pressure & surface run-off erosion.",
        "start_point": "Mawkdok Viewpoint",
        "end_point": "Sohra Market",
        "is_single_access": True,
    },
    {
        "road_id": "RD-NH-54-HAFLONG",
        "name": "NH-54 Hill Section Rail-Road Link",
        "road_class": "national_highway",
        "zone_id": "NER-ASM-004",
        "status": "open",
        "blockage_reason": None,
        "start_point": "Lumding Junction",
        "end_point": "Haflong Town",
        "is_single_access": False,
    },
    {
        "road_id": "RD-NH-2-KOHIMA",
        "name": "NH-2 Dimapur - Kohima Highway",
        "road_class": "national_highway",
        "zone_id": "NER-NAG-009",
        "status": "open",
        "blockage_reason": None,
        "start_point": "Dimapur Bypass",
        "end_point": "Kohima North",
        "is_single_access": False,
    },
]

SEED_OFFICERS = [
    {
        "user_id": "usr-dmo-kameng",
        "username": "officer_kameng",
        "full_name": "Tashi Dorjee",
        "role": "disaster_management_officer",
        "district": "West Kameng",
        "escalation_level": 1,
        "contact_number": "+919436012345",
        "hashed_password": "demo_hashed_secret",
    },
    {
        "user_id": "usr-dmo-shillong",
        "username": "officer_shillong",
        "full_name": "Dr. Wanphrang Lyngdoh",
        "role": "disaster_management_officer",
        "district": "East Khasi Hills",
        "escalation_level": 1,
        "contact_number": "+919436054321",
        "hashed_password": "demo_hashed_secret",
    },
    {
        "user_id": "usr-sdma-director",
        "username": "sdma_director",
        "full_name": "Lalitha Sharma",
        "role": "disaster_management_officer",
        "district": None,
        "escalation_level": 2,
        "contact_number": "+919436099999",
        "hashed_password": "demo_hashed_secret",
    },
]
