"""Curated North Eastern Region geospatial hazard monitoring zones."""

SEED_ZONES = [
    {
        "zone_id": "NER-ARU-001",
        "name": "Kameng Sector - Bhalukpong Ridge",
        "district": "West Kameng",
        "state": "Arunachal Pradesh",
        "latitude": 27.2645,
        "longitude": 92.4159,
        "avg_slope_deg": 38.5,
        "avg_elevation_m": 1240.0,
        "rainfall_24h": 178.0,
        "rainfall_72h": 320.0,
        "insar_deformation": -24.6,
        "soil_moisture": 89.2,
        "ndvi_index": 0.38,
    },
    {
        "zone_id": "NER-MEG-001",
        "name": "Sohra (Cherrapunji) Sector A",
        "district": "East Khasi Hills",
        "state": "Meghalaya",
        "latitude": 25.2700,
        "longitude": 91.7300,
        "avg_slope_deg": 38.2,
        "avg_elevation_m": 1430.0,
        "rainfall_24h": 198.4,
        "rainfall_72h": 342.1,
        "insar_deformation": -21.4,
        "soil_moisture": 88.5,
        "ndvi_index": 0.38,
    },
    {
        "zone_id": "NER-MEG-002",
        "name": "East Khasi Hills - Sohra Canyon",
        "district": "East Khasi Hills",
        "state": "Meghalaya",
        "latitude": 25.5788,
        "longitude": 91.8933,
        "avg_slope_deg": 34.0,
        "avg_elevation_m": 1510.0,
        "rainfall_24h": 142.0,
        "rainfall_72h": 268.0,
        "insar_deformation": -12.8,
        "soil_moisture": 78.5,
        "ndvi_index": 0.42,
    },
    {
        "zone_id": "NER-MAN-003",
        "name": "Ukhrul Central Escarpment",
        "district": "Ukhrul",
        "state": "Manipur",
        "latitude": 25.1167,
        "longitude": 94.3667,
        "avg_slope_deg": 41.2,
        "avg_elevation_m": 1660.0,
        "rainfall_24h": 164.0,
        "rainfall_72h": 298.0,
        "insar_deformation": -19.2,
        "soil_moisture": 84.0,
        "ndvi_index": 0.39,
    },
    {
        "zone_id": "NER-ASM-004",
        "name": "Dima Hasao - Haflong Hill Cut",
        "district": "Dima Hasao",
        "state": "Assam",
        "latitude": 25.1762,
        "longitude": 93.0234,
        "avg_slope_deg": 32.8,
        "avg_elevation_m": 680.0,
        "rainfall_24h": 138.0,
        "rainfall_72h": 242.0,
        "insar_deformation": -11.4,
        "soil_moisture": 76.1,
        "ndvi_index": 0.46,
    },
    {
        "zone_id": "NER-SKM-014",
        "name": "Dikchu - Singtam Faultline",
        "district": "Gangtok",
        "state": "Sikkim",
        "latitude": 27.3500,
        "longitude": 88.5500,
        "avg_slope_deg": 42.0,
        "avg_elevation_m": 1720.0,
        "rainfall_24h": 88.2,
        "rainfall_72h": 164.0,
        "insar_deformation": -18.2,
        "soil_moisture": 74.0,
        "ndvi_index": 0.44,
    },
    {
        "zone_id": "NER-MIZ-007",
        "name": "Aizawl North Ridge",
        "district": "Aizawl",
        "state": "Mizoram",
        "latitude": 23.7271,
        "longitude": 92.7176,
        "avg_slope_deg": 35.0,
        "avg_elevation_m": 1132.0,
        "rainfall_24h": 94.0,
        "rainfall_72h": 180.0,
        "insar_deformation": -9.8,
        "soil_moisture": 71.2,
        "ndvi_index": 0.49,
    },
    {
        "zone_id": "NER-NAG-009",
        "name": "Kohima - Zubza Slope Corridor",
        "district": "Kohima",
        "state": "Nagaland",
        "latitude": 25.6701,
        "longitude": 94.1077,
        "avg_slope_deg": 36.4,
        "avg_elevation_m": 1444.0,
        "rainfall_24h": 105.0,
        "rainfall_72h": 195.0,
        "insar_deformation": -14.2,
        "soil_moisture": 75.0,
        "ndvi_index": 0.43,
    },
]
