apiVersion: apps/v1
kind: Deployment
metadata:
  name: landslide-web
  labels:
    app: landslide-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: landslide-web
  template:
    metadata:
      labels:
        app: landslide-web
    spec:
      containers:
        - name: web
          image: landslide-web:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://landslide-api-service:8000"
---
apiVersion: v1
kind: Service
metadata:
  name: landslide-web-service
spec:
  type: LoadBalancer
  selector:
    app: landslide-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
